### ISSUE TITLE
测试

### ISSUE THREAD

**Issue by SUT-pxc** [YQ-097/BTSFusion#2]
作者您好，我跑测试只能测TNO的一张图，请问怎么设置测试MSRS或者其他数据集呀

**Comment by SUT-pxc** [comment]
并且，一次测试一张，请问怎样更改设置，让其遍历整个数据集，全部测试呀

**Comment by YQ-097** [comment]
修改测试文件test1_image.py中的测试集路径`if in_c == 1:
		test_path = "./images/TNO/"
	else :
		test_path = r"./images/MSRS/"`可更改数据集。
修改for循环次数即可跑完整的数据集，如有40张测试图片则`for i in range(40):`。
