### ISSUE TITLE
作者你好，感谢你的公开代码，目前我直接测试或者训练生成的图片都有问题，请问下您怎么解决？

### ISSUE THREAD

**Issue by JAWILU** [YQ-097/BTSFusion#3]
![1](https://github.com/YQ-097/BTSFusion/assets/147688830/9f34a718-cd69-4729-86a9-7f587f711e9b)

**Comment by YQ-097** [comment]
你好，这是通过什么操作生成的图像？是运行python test1_image.py生成的吗？

**Comment by YQ-097** [comment]
不知是否你使用的环境有问题，我已更新代码，修改了utils.py中使用的scipy库函数的部分。希望对你有所帮助。

**Comment by JAWILU** [comment]
你好，能方便加个qq好友吗？1944335480，感谢您

**Comment by JAWILU** [comment]
我已经成功运行test出来代码？请问下您的训练集可以分享一下吗？或者是怎么放置数据集？谢谢

**Comment by JAWILU** [comment]
作者您好，我在运行mfnet代码时遇到问题，请问您论文中语义分割代码怎么运行流程？示例中两张图片可以生生产，但我自己加入任何任何一张图片都运行失败，期待您的解答，谢谢！
![1716880443197](https://github.com/YQ-097/BTSFusion/assets/147688830/e1e9e7cf-3912-4105-bcdd-7d0a55212a32)

**Comment by YQ-097** [comment]
你好，BTSFusion中的Mask图并不是通过MFNet得到的，不过你采用分割算法去制作Mask图也是可以的。这是BTSFusion所用的训练集，希望对你有所帮助。链接：https://pan.baidu.com/s/1rqxry1aUrtAaFjjgnWEh0w?pwd=suep 提取码：suep

**Comment by JAWILU** [comment]
十分感谢您的分享，但是可以指点一下这种对比图片的制作吗？我接下来做出成果后撰写文章定会将您两篇文章引用谢谢！
![image](https://github.com/YQ-097/BTSFusion/assets/147688830/d1d41bb8-5d77-4725-802e-9903ce51e6c5)

**Comment by YQ-097** [comment]
这是使用同一分割算法对每种对比方法的融合结果进行分割，然后将结果在Word中排版整理（抬头的标签也是后续画上去的）。
