### ISSUE TITLE
代码好像不够完整

### ISSUE THREAD

**Issue by yufffffffffff** [YQ-097/BTSFusion#4]
作者这个代码好像不全啊，能把完整代码发下吗，2296085080@qq.com，谢谢

**Comment by YQ-097** [comment]
你好，这是完整的代码，请问你觉得是哪部分代码缺失了。

**Comment by yufffffffffff** [comment]
guided_filter、bilateral_filter等这几个filter并没有函数调用啊，是否参与到了损失函数训练中

**Comment by YQ-097** [comment]
guided_filter在utils.py中被引用。bilateral_filter是用来进行消融对比的，不作为最终模型的一部分。
